name: PR And Main Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: tests
        run: |
          set +x  
          sudo timedatectl set-timezone "America/Chicago" 
          CURREPOCH=`date +%s`
          CURRDATETIME=`date -d @$CURREPOCH`

          set -x 
          echo "Chicago DateTime: $CURRDATETIME"
          set +x 
        
          # Now do EST
          sudo timedatectl set-timezone "America/New_York"
          CURREPOCH=`date +%s`
          CURRDATETIME=`date -d @$CURREPOCH`

          set -x 
          echo "NY DateTime: $CURRDATETIME"

          # Now do PST
          sudo timedatectl set-timezone "America/Los_Angeles"
          CURREPOCH=`date +%s`
          CURRDATETIME=`date -d @$CURREPOCH`

          set -x 
          echo "NY DateTime: $CURRDATETIME"

          # can also use America/Louisville
      - name: tests
        run: |
          set -x 
          
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.45.0/opa_linux_amd64
          chmod u+x ./opa

          terraform --version
          ./opa version

          # Fake
          AWS_ACCESS_KEY_ID="AK123451234512345"
          AWS_SECRET_ACCESS_KEY="DHHHDAUUGHGHGHEIUIAHGHGH"
          AWS_REGION="us-east-1"
          
          # Set Up Terraform
          terraform init
          terraform plan --out tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

          # OPA Policy Checks
          opa exec --decision terraform/analysis/authz --bundle policy/ tfplan.json | jq -r ".result[] |.result"