name: PR And Main Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: tests
        run: |
          set +x 
          TIMEZONE="America/Chicago"     
          sudo echo $TIMEZONE > /etc/timezone  
          sudo cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
          TZ=America/Chicago

          CURREPOCH=`date +%s`
          AHEADEPOCH=$(($CURREPOCH + 3600))
          BEHINDEPOCH=$(($CURREPOCH - 3600))

          CURRDATETIME=`date -d @$CURREPOCH`
          AHEADDATETIME=`date -d @$AHEADEPOCH`
          BEHINDDATETIME=`date -d @$BEHINDEPOCH`

          set -x 
          echo "Current: $CURRDATETIME"
          echo "Ahead: $AHEADDATETIME"
          echo "Behind: $BEHINDDATETIME"

          printf '%(%FT%T%z)T\n' $CURRDATETIME

          TZ=America/Chicago bash -c 'printf "%(%c)T\n" 0'
          printf '%(%FT%T%z)T\n' $CURRDATETIME

      - name: tests
        run: |
          set -x 
          terraform --version
          
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.45.0/opa_linux_amd64

          ls -ltra
          
          chmod u+x ./opa

          ./opa version