name: PR And Main Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: tests
        run: |
          set +x 
          CURREPOCH=`date +%s`
          AHEADEPOCH=$(($CURREPOCH + 3600))
          BEHINDEPOCH=$(($CURREPOCH - 3600))

          CURRDATETIME=`date -d @$CURREPOCH`
          AHEADDATETIME=`date -d @$AHEADEPOCH`
          BEHINDDATETIME=`date -d @$BEHINDEPOCH`

          set -x 
          echo "Current: $CURRDATETIME"
          echo "Ahead: $AHEADDATETIME"
          echo "Behind: $BEHINDDATETIME"
      - name: tests
        run: |
          set -x 
          terraform --version
          
          sudo apt update
          sudo apt install -y opa

          opa version