name: PR And Main Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: tests
        run: |
          set +x  
          sudo timedatectl set-timezone "America/Chicago" 
          #TZ=America/Chicago

          CURREPOCH=`date +%s`
          CURRDATETIME=`date -d @$CURREPOCH`
          set -x 
          echo "Chicago DateTime: $CURRDATETIME"

          sudo timedatectl set-timezone "America/New_York" 
          #TZ=America/Chicago

          CURREPOCH=`date +%s`
          CURRDATETIME=`date -d @$CURREPOCH`
          set -x 
          echo "NY DateTime: $CURRDATETIME"

      - name: tests
        run: |
          set -x 
          terraform --version
          
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.45.0/opa_linux_amd64

          ls -ltra

          chmod u+x ./opa

          ./opa version